### ISSUE TITLE
About ndt-mapping

### ISSUE THREAD

**Issue by AlexandrZabolotny** [daohu527/ndt_mapping#1]
Hello!
For which version of Apollo was ndt mapping created?

**Comment by daohu527** [comment]
I am using Apollo 5.0. In fact, as long as the topic is the same and the pose and pcd files can be extracted, any version is possible.

**Comment by AlexandrZabolotny** [comment]
I am using Apollo pre6. When build module I get next error

![Screenshot from 2021-05-26 10-00-15](https://user-images.githubusercontent.com/61351599/119616422-436afc00-be09-11eb-8a0e-089b64bb773a.png)

**Comment by daohu527** [comment]
Which compile command do you use?

Apollo's compilation has made some changes, now I am not sure what's the problem.  
You can try to compile the entire localization module instead of compiling this tool separately
```
./apollo.sh build localization
```

**Comment by AlexandrZabolotny** [comment]
I built this module with Apollo 5. Everything is working now
