### ISSUE TITLE
ndt-mapping.cc

### ISSUE THREAD

**Issue by li123il** [daohu527/ndt_mapping#10]
The following error occurred after using the code
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0411 15:01:19.780390 13126 ndt_mapping.cc:118] [ndt_mapping]pcd_poses: 209 ,pcd_indices: 209
I0411 15:01:19.780512 13126 ndt_mapping.cc:131] [ndt_mapping]Pcd file size: 209
I0411 15:01:20.041620 13126 ndt_mapping.cc:222] [ndt_mapping]NDT sequence id: 1 fitness_score: 0.541877 has_converged: 1 final_num_iteration: 1 transformation_probability: 0.999541
Segmentation fault (core dumped)

**Comment by daohu527** [comment]
Can you add some logs, or see the reason for the coredump.
```
gdb ./bazel-bin/modules/localization/msf/local_tool/ndt_mapping/ndt_mapping  data/core/xxx.core
```

**Comment by li123il** [comment]
![问题3](https://user-images.githubusercontent.com/100338884/162866298-5eaac1cc-52a8-4e26-89b8-40a39db1d8d3.png)

**Comment by daohu527** [comment]
There is no valid coredump information here, so it may be necessary to add some log to find out which code is crashed
You can follow below code to add log in the code
```c++
  int i = 0;
  while(!async_buffer_ptr->IsEnd()) {
   AINFO << "while loop count: " << ++i;
    PointCloudPtr cloud_ptr = async_buffer_ptr->Get();
    if (cloud_ptr) {
      LidarProcess(cloud_ptr);
    }
  }
  AINFO << "loop ended!";
```

**Comment by eggiiiiiii** [comment]
Add to which line？

**Comment by li123il** [comment]
![Uploading 问题4.png…]()

**Comment by li123il** [comment]
![问题4](https://user-images.githubusercontent.com/100338884/162875853-2d699596-2b46-4033-bce4-d25e783acb72.png)

**Comment by daohu527** [comment]
In short, you should check that the input PointCloud is well. e.g. is some property empty.

Also you can add more logs in `LidarProcess` and find which line cause the error.

**Comment by li123il** [comment]
I can see if only two PCD files are loaded in the running result, which indicates whether there is a problem from the third PCD file？

**Comment by li123il** [comment]
Whcih is LidarProcess?

**Comment by li123il** [comment]
![2022-04-12 14-51-05 的屏幕截图](https://user-images.githubusercontent.com/100338884/162898574-16d63a13-826a-4920-b478-8266b89293cf.png)
Is there a problem with the pose file starting from 4?

**Comment by li123il** [comment]
Because lidar_ loc is empty？
![2022-04-12 14-55-11 的屏幕截图](https://user-images.githubusercontent.com/100338884/162899035-ca7c669e-525d-46eb-91f9-b423c869d688.png)

**Comment by li123il** [comment]
I've solved it，Thank you very much

**Comment by daohu527** [comment]
You're welcome, if you can, can you point out the reason for helping others!

**Comment by li123il** [comment]
if (is_first_map=true) {
    *map_ptr += *scan_ptr;
    is_first_map = false;
    return;
  }

**Comment by li123il** [comment]
add “is_first_map=true”can solve it

**Comment by daohu527** [comment]
There is a big problem with the code below. If you want to compare values, you should use `is_first_map == true`. So I don't think you found the real problem
```
if (is_first_map=true) {
```

**Comment by li123il** [comment]
you are right ,and Why is my picture like this? How to modify it?
![重合](https://user-images.githubusercontent.com/100338884/163302282-5fb56e63-be4f-48c2-9ee6-5afb4324aada.png)

**Comment by li123il** [comment]
I feel that the image I made is messy and not as clear as yours. Is it a parameter problem? I was moving during the recording. Could it be because of the problem of movement, so the superposition would look messy? If you are still during recording, the final map generated is clear and not chaotic.

**Comment by li123il** [comment]
我检查了一遍应该是LidarProcess有问题，但是我不知道如何解决，您有什么建议？

**Comment by daohu527** [comment]
I suggest that you understand the principle, you can use only 2 frames or 3 frames of pose, stitch a point cloud and try again

The way I solve the problem is to find the problem and fix it, so you can ask yourself:
1. what's the problem
2. what caused it

The whole process has been verified, either there is a problem with your lidar pose, or there is a problem with the point cloud. If it's a crash problem you can add a log to find out which line of code caused the crash

Your biggest difficulty is being unfamiliar with the entire system, which takes time and some patience to learn.

**Comment by daohu527** [comment]
@li123il  I tested it, apollo5.0 can work normally, but 6.0 not.

At the moment I don't know what the problem is, it might take some time. You can use apollo5.0 to build a map, it doesn't need to change anything, just switch branches and follow the same steps
