### ISSUE TITLE
ndt_mapping

### ISSUE THREAD

**Issue by mbing123** [daohu527/ndt_mapping#13]
Hello,Mr.daohu!
my apollo car computer is apollo5.5. And clone the ndt_mapping_r5.0.0.
Now GPU compilation and NDT compilation are successful.
However, I have the following problems when create a map
I want to know what caused this problem, I would appreciate it if you could help me!!!
![Screenshot from 2022-04-30 18-40-11](https://user-images.githubusercontent.com/104626637/166102796-54eafc04-e5b7-4c9c-a369-446c8b4e5001.png)

**Comment by daohu527** [comment]
`failed to find match for field 'intensity'` is an error report by the pcl library. It may be because the intensity information of the point cloud cannot be read or is wrong, but the intensity information is not currently used in NDT mapping

**Comment by mbing123** [comment]
but I can't get a map just like following picture show
so, what's wrong 
what can I do for it
![Screenshot from 2022-05-03 09-52-16](https://user-images.githubusercontent.com/104626637/166394163-c83613a7-3039-401b-90a5-c72a36177aa5.png)

**Comment by daohu527** [comment]
What is your version of Apollo? I found out that the pcl library for apollo 6.0 has been modified and caused the core dump problem.

But your error shows that saving the map has already started. You can check `map_ptr` is nullptr or it's an error report by PCL
```
  CHECK(map_ptr != nullptr) << "map is null";
  PointCloudPtr align_map_ptr(new PointCloud());
  pcl::transformPointCloud(*map_ptr, *align_map_ptr, align_pose.matrix().cast<double>());
```

**Comment by mbing123** [comment]
My version of Apollo is r5.5.0, and clone the ndt_mapping_r5.0.0.
![Screenshot from 2022-05-04 10-51-09](https://user-images.githubusercontent.com/104626637/166617287-4a32b20f-2240-44b8-bceb-df567c9b5910.png)

**Comment by mbing123** [comment]
In the beginning, it can't compile 

![Screenshot from 2022-05-04 11-09-08](https://user-images.githubusercontent.com/104626637/166619579-7fad3252-d026-483f-a67f-dde4588fbe67.png)

I then added two lines to the ndt_mapping/BUILD file to make it compile

![Screenshot from 2022-05-04 11-15-56](https://user-images.githubusercontent.com/104626637/166619582-3728c68d-a9c2-43d7-ab62-ea017b899a88.png)

**Comment by daohu527** [comment]
@mbing123 I found there is a `_mm256_load_pd` error. fix it now
