### ISSUE TITLE
ndt_mapping

### ISSUE THREAD

**Issue by mbing123** [daohu527/ndt_mapping#15]
When I extract the pcd file and pose file from the bag,I can get the following contect
but gnss_loc.txt and lidar_loc.txt the two files are empty.
What's wrong with it?
![Screenshot from 2022-05-07 16-44-08](https://user-images.githubusercontent.com/104626637/167246894-fcf240b5-fe19-454a-a601-fcf0c99a5673.png)

**Comment by daohu527** [comment]
You should check the topic is in your record file
gnss_loc_topic `/apollo/localization/measure_gnss` 
lidar_loc_topic  `/apollo/localization/measure_lidar`

Since we only need `odometry_loc.txt` so it's doesn't matter.
odometry_loc_topic `/apollo/localization/pose`

**Comment by daohu527** [comment]
Since the issue has not been activated for a long time, I will close it first
