### ISSUE TITLE
How to generate Ndt map for apollo ndt localization?

### ISSUE THREAD

**Issue by sinopec** [daohu527/ndt_mapping#18]
Thanks author, I can use the code generate a whole  pointcloud map (PCD), but how can I transform the pcd into the format  which canbe used in apollo ndt localization as a ndt local map?

**Comment by daohu527** [comment]
There is a tool to generate map in apollo, I will give the reference documentation soon!

**Comment by daohu527** [comment]
You can refer to the following tools in apollo to generate the NDT map.
```
modules/localization/ndt/map_creation
```

**Comment by mbing123** [comment]
When drawing map using RoadRunner to export Apollo format, how to eliminate the Z coordinates in .txt file.

**Comment by daohu527** [comment]
You can write a script to remove the z.
