### ISSUE TITLE
Can't use multiple "--bag_file" to extract multiple bag files

### ISSUE THREAD

**Issue by mbing123** [daohu527/ndt_mapping#19]
I can use multiple "--bag_file" to extract multiple bag files (apollo r5.5) 
What can I do for it to extract multiple bag file one time
![Screenshot from 2022-07-24 10-07-36](https://user-images.githubusercontent.com/104626637/180629316-9b24cb40-25f7-405d-a2a6-8975707395fe.png)

**Comment by daohu527** [comment]
I also noticed the difference, which version of apollo have the problem?

**Comment by mbing123** [comment]
apollo r5.5.0

**Comment by daohu527** [comment]
@mbing123 apollo r5.5.0 don't support multiple `--bag_file`. You can refer to other versions to implement it, of course I forget whether it is 5.0 or 6.0

**Comment by mbing123** [comment]
Do you mean that I can refer to version 5.0 or 6.0 to modify the 5.5 related files? Or replace version 5.5 all?

**Comment by daohu527** [comment]
ndt_mapping have error with apollo 6.0 for now. you can just ref the `cyber_record_parser` code alone.

**Comment by mbing123** [comment]
I'll try it now. Thanks

**Comment by mbing123** [comment]
When I made a map of 43 files, it took me 80 hours to make an output.pcd. Is it normal to take such a long time?

**Comment by daohu527** [comment]
No, normally 43 files will be fast in a few minutes. 

When the outfile gets bigger, the speed will get slower. Pls check the output file size

**Comment by mbing123** [comment]
I mean 43 recorded files, over 25,000 pcd files when unzipped. The resulting output.pcd file size is 759M

**Comment by daohu527** [comment]
That seems normal, since there is no parallel processing at the moment. 

Decreasing how the output point cloud is matched can reduce the time, but I haven't tried it yet. For example, only a portion of the output point cloud is captured for matching instead of all

**Comment by mbing123** [comment]
I see. I really appreciate it

**Comment by daohu527** [comment]
@mbing123 By comparing the previous 3 frames instead of the entire map, the speed has now been greatly improved. I created a map about 600 frames which cost 2600s (43min)
