### ISSUE TITLE
Error in build on apollo 7.0

### ISSUE THREAD

**Issue by Ladanovasv** [daohu527/ndt_mapping#20]
`apollo.sh build_gpu`
![photoeditorsdk-export](https://user-images.githubusercontent.com/47398458/189296402-950aec7e-1564-4d63-8920-09b9fc13f73b.png)

**Comment by daohu527** [comment]
I'm working on it, it might be a problem with the pcl library

**Comment by daohu527** [comment]
@Ladanovasv You can use the latest master to create the map. 

Note that the data is decompressed in apollo, then copied to the container of ndt_mapping, and finally the map is generated with ndt_mapping
