### ISSUE TITLE
This repo support ros?

### ISSUE THREAD

**Issue by wangfei-tech** [daohu527/ndt_mapping#25]
Hello， thanks for your kind work!

1.I use ros1 and record datas by rosbag.
2.my  lidar is robosense-128 beams.

This is my workspace, I have some quesetions:
I use use python to convert data format,but But the established map merges into a whole.Is this caused by the failure to calibrate the lidar and IMU?

**Comment by wangfei-tech** [comment]
@daohu527 Looking forward to your reply！

**Comment by daohu527** [comment]
No, it is system independent. You only need to decompress the corresponding point cloud and IMU attitude information.

Simply put, we need the IMU to initialize and then perform NDT matching

**Comment by wangfei-tech** [comment]
@daohu527  Thanks for your prompt reply！
I imitated the cyber_record_parser.py in your tools to extract my IMU and GPS data. I would like to ask whether the extraction of point cloud and IMU data can be completed using a processing method similar to cyber_record_parser.py?
Looking forward to your reply!

**Comment by daohu527** [comment]
Yes, the tool already can decompress the record, but not the ros bag.

for ros bag you can use python module `rosbags`

**Comment by wangfei-tech** [comment]
@daohu527  Thank you for your timely reply, I will try to use rosbags for data processing, I will keep this issue open for a while in case there will be new questions to ask you.

**Comment by wangfei-tech** [comment]
I will close the issue，thanks ! @daohu527
