### ISSUE TITLE
Use ndt-map for Apollo

### ISSUE THREAD

**Issue by AlexandrZabolotny** [daohu527/ndt_mapping#3]
Hello
Answer me please.
How can I use this map for ndt localization in Apollo?

**Comment by daohu527** [comment]
This map is not used as a location map, there are other ways to create a location map. I am still optimizing it. 

I will post the tutorial when I’m ready

**Comment by daohu527** [comment]
You can use point cloud maps to make NDT location maps. 

At present, this tool has been implemented in the ndt location module. I will add this document later

**Comment by AlexandrZabolotny** [comment]
It will be an interesting and very useful tool.

**Comment by WhutChengjun** [comment]
How to build the localization module in apollo? The system of our vehicle is apollo5.5. Firstly, i copied the entire directory ndt_mapping to apollo's modules/localization/msf/local_tool/, secondly, i used the command "bash apollo.sh build_opt.gpu" in the docker environment for compiling, but compilation failed, the error is 
![微信图片_20211218165247](https://user-images.githubusercontent.com/51869423/146666727-1f2a16fe-34e8-425d-9b4b-0689bd5cbaa9.jpg)

**Comment by daohu527** [comment]
## question
You can try `bash apollo.sh build`.

`bash apollo.sh build_opt.gpu` is gpu mode and I'm not sure it will work. 

## addition
I found that I overlooked a problem. I assume that the coordinates of IMU and lidar are the same. In fact, the system may not be like this, so it is best to add IMU to Lidar coordinate conversion.
