### ISSUE TITLE
Cannot build Apollo6.0 with ndt_mapping directory

### ISSUE THREAD

**Issue by BIGFatming** [daohu527/ndt_mapping#5]
I tried **bash apollo.sh build_opt_gpu**, but system report an error, as shown in image
![sunlogin_20220118154104](https://user-images.githubusercontent.com/73275810/149894932-92423bee-9f4e-4e0c-afc0-df0c5c095c75.JPG)
Then I tried **bash apollo.sh build**, but the same error is raised,
![sunlogin_20220118155315](https://user-images.githubusercontent.com/73275810/149895835-a6b2b207-efa7-4ca5-8914-026ae5ef62fc.JPG)

Maybe this project dose not fit Apollo6.0?

**Comment by daohu527** [comment]
I will test in Apollo6.0 and feedback soon.

**Comment by daohu527** [comment]
@BIGFatming 
There are some changes in apollo 6.0. I have fixed the compilation problem https://github.com/daohu527/ndt_mapping/pull/6, but I haven't had time to test the whole process. If there are problems later, you can raise another issue.

**Comment by BIGFatming** [comment]
@daohu527 get it
